spring:
  jackson.default-property-inclusion: non_null
  data:
    mongodb:
      host: localhost
      database: loyalty
      port: 27017

---

spring.profiles: prod

spring:
  data:
    mongodb:
      host: mongodb
