server.port: 8080

spring:
  jackson.default-property-inclusion: non_null
  data:
    mongodb:
      database: Canteen
      host: localhost
      port: 27017

---

spring.profiles: prod

spring:
  data:
    mongodb:
      host: mongodb